global:
  scrape_interval:     60s 
  evaluation_interval: 60s 
  external_labels:
    cluster: prometheus
    replica: '0'

alerting:
  alert_relabel_configs:
  - regex: 'replica'
    action: labeldrop
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager- $:9093
      - alertmanager- $:9093

scrape_configs:
  - job_name: metrics_15s
    scheme: https
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
           - '{job=~"federate"}'
    static_configs:
      - targets: ['Your-Target']

  - job_name: metrics_15s
    scheme: https
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
           - '{job=~"federate"}'
    static_configs:
      - targets: ['Your-Target']
